#+BEGIN_HTML
---
layout: post
title: "グローバルゲームジャム2014 参加してきました。GlobalGameJam2014 - TEAM Sayaka #ggj14zenrin"
date: 2014-01-27 22:14
comments: true
categories: 
description: 
keywords: GGJ Unity3D Unity2D OculusRift EyeTribe
---
#+END_HTML

* Global Game Jamとは
  - 全世界同時開催の世界最大のGameJam（GameJamとは決められた短い時間でゲーム作るイベント）
  - 2014年の1/24から1/26の3日間。48時間で決められたテーマにそったゲームを作るイベント。
  - 海外公式によると、全世界で73カ国、485会場、4226本のゲームが作られた。
  - 開発するものについては、デジタルのPCゲームからアナログまで何でもあり。
  - チームについては、事前に個人エントリー時のアンケートから、リーダーとメインプログラマを会場側が指定。
  - メンバーはランダムに振られて5人くらいでチームを組み、完成を目指す。
    
* 各種情報
  - 公式（本家 英） [[http://globalgamejam.org/][Global Game Jam]]
  - 公式（日） [[http://ggj.igda.jp/][Global Game Jam JAPAN | Innovation, Collaboration, Experimentation! Jan. 24~26, 2014]]
  - 参加会場（日） [[http://ggj2014-zenrin.peatix.com/][Global Game Jam 2014 ZENRIN ODAIBA]]
  - 参加会場（英） [[http://globalgamejam.org/2014/jam-sites/global-game-jam-2014-zenrin-odaiba][Global Game Jam 2014 ZENRIN ODAIBA | Global Game Jam]]
  - 開催会場 [[http://globalgamejam.org/status][Live Status | Global Game Jam]]
  - 作られたゲーム [[http://globalgamejam.org/2014/games][Games 2014 | Global Game Jam]]
  - Twitter [[https://twitter.com/search?q=ggj14zenrin][#ggj14zenrin]]
  - USTREAM GGJお台場会場 [[http://www.ustream.tv/recorded/43064931][中間発表]] / [[http://www.ustream.tv/recorded/43103097][最終発表]]

* 参加のきっかけ
  =@tsubaki\_t1= さんのRTを見て
  #+begin_html
  <blockquote class="twitter-tweet" data-cards="hidden" lang="ja"><p>GGJ お台場会場参加お待ちしております！快適な環境・設備が揃っておりますよー！大江戸温泉もありますよー！&#10;<a href="http://t.co/pfc1dqfPiZ">http://t.co/pfc1dqfPiZ</a> <a href="https://twitter.com/search?q=%23ggj&amp;src=hash">#ggj</a> <a href="https://twitter.com/search?q=%23ggj14jp&amp;src=hash">#ggj14jp</a> <a href="https://twitter.com/search?q=%23unity&amp;src=hash">#unity</a> <a href="https://twitter.com/search?q=%23unity3d&amp;src=hash">#unity3d</a> <a href="https://twitter.com/search?q=%23game&amp;src=hash">#game</a> jam</p>&mdash; Junya.T (@Jun_ya_) <a href="https://twitter.com/Jun_ya_/statuses/421664004855963648">2014, 1月 10</a></blockquote>
  <script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
  #+end_html
  とても疲れていたのでとにかく温泉に入ってゆっくり、こころとからだをやすめたかった。死にそうになったけど。。
 
* つづく
